import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardFeaturedProjectComponent } from '../card-featured-project/card-featured-project.component';
import { TranslatePipe } from '../../pipes/translate.pipe';
import { FeatureProject } from '../../../core/models/featureProject';

@Component({
  selector: 'app-project',
  imports: [CommonModule, CardFeaturedProjectComponent, TranslatePipe],
  templateUrl: './project.component.html',
  styleUrl: './project.component.css',
})
export class ProjectComponent {
  readonly featuredProjects: FeatureProject[] = [
    {
      title: 'Orkesta',
      image: {
        src: 'assets/orkesta.png',
        alt: 'Orkesta - Digital Invitation System Dashboard',
      },
      duration: 'August 2025 - Present',
      description: 'projects.orkesta.description',
      technologies: [
        'Angular 19',
        'NestJS 11',
        'TypeScript',
        'PostgreSQL',
        'Redis',
        'Prisma ORM',
        'Docker',
        'Railway',
        'GitHub Actions',
        'TailwindCSS',
        'Angular Material',
        'WhatsApp Integration',
        'Server-Side Rendering',
        'Static Site Generation',
        'Standalone Components',
        'Signals API',
        'Lazy Loading',
        'Code Splitting',
        'Performance Optimization',
        'Web Accessibility',
        'Component-Based Architecture',
        'Reactive Programming',
        'Modern JavaScript',
        'Web Development',
        'UI/UX Design',
        'Lead Generation',
      ],
      link: 'https://orkesta.com.mx',
    },
    {
      title: 'Real del Paso',
      image: {
        src: 'assets/realdelpaso.png',
        alt: 'Real del Paso - Premium Event Venue Website',
      },
      duration: '2025 - Present',
      description: 'projects.realDelPaso.description',
      technologies: [
        'Angular 20',
        'TypeScript',
        'Tailwind CSS',
        'RxJS',
        'SSR/SSG',
        'Express.js',
        'JSON-LD',
        'SEO Optimization',
        'Responsive Design',
        'Standalone Components',
        'Signals API',
      ],
    },
    {
      title: 'Swiss Premier - Mobile App',
      image: {
        src: 'assets/swiss_mobile.png',
        alt: 'Swiss Premier Mobile App - Debt Collection Application',
      },
      duration: 'May 2024 - Aug 2025',
      description: 'projects.swiss.mobile.description',
      technologies: [
        'Angular 18',
        'Ionic 8',
        'Capacitor',
        'TypeScript',
        'SQLite',
        'PDFMake',
        'Angular Material',
        'RxJS',
        'Sass',
        'Android Studio',
        'Xcode',
        'Firebase',
        'JWT Authentication',
        'PWA',
      ],
    },
    {
      title: 'Swiss Premier - Web',
      image: {
        src: 'assets/swiss_admin.png',
        alt: 'Swiss Premier Web Dashboard - Administrative Interface',
      },
      duration: 'June 2025 - Aug 2025',
      description: 'projects.swiss.web.description',
      technologies: [
        'Angular 18',
        'Tailwind CSS',
        'Angular Material',
        'TypeScript',
        'Firebase',
        'RxJS',
        'Lucide Icons',
        'PDFMake',
        'Moment.js',
        'JWT Authentication',
        'Responsive Design',
        'PWA',
      ],
    },
    {
      title: 'IMTPaveExpress - Web',
      image: {
        src: 'assets/imtpx.png',
        alt: 'IMTPaveExpress Web Application - Pavement Analysis Platform',
      },
      duration: 'March 2024 - Aug 2025',
      description: 'projects.imtpx.web.description',
      technologies: [
        'Angular 17',
        'TypeScript',
        'Angular Material',
        'RxJS',
        'Chart.js',
        'Bootstrap',
        'SCSS',
        'Firebase',
        'JWT Authentication',
        'Angular CDK',
        'Ng-Bootstrap',
        'jsPDF',
        'XLSX',
        'Moment.js',
        'Responsive Design',
      ],
    },
    {
      title: 'Cotizly',
      image: {
        src: 'assets/cotizly.png',
        alt: 'Cotizly SaaS Platform - Quote and Order Management System',
      },
      duration: 'June 2025 - current',
      description: 'projects.cotizly.description',
      technologies: [
        'Angular 19',
        'NestJS',
        'TypeScript',
        'PostgreSQL',
        'TailwindCSS',
        'Angular Material',
        'JWT',
        'Firebase',
        'Docker',
        'Swagger',
        'RxJS',
        'TypeORM',
        'Heroku',
        'CI/CD',
      ],
    },
    {
      title: 'IMTPaveExpress - Backend (Calculations)',
      image: {
        src: 'assets/imtpx_calculos.png',
        alt: 'IMTPaveExpress Backend - Pavement Engineering Calculations API',
      },
      duration: 'March 2024 - Aug 2025',
      description: 'projects.imtpx.calculations.description',
      technologies: [
        'Java 17',
        'Spring Boot 3.5.3',
        'Maven',
        'Lombok',
        'Micrometer',
        'Spring Cache',
        'Spring Actuator',
        'Docker',
        'Nginx',
        'JWT Authentication',
        'Swagger/OpenAPI',
        'Caffeine Cache',
        'Bean Validation',
        'REST API',
      ],
    },
    {
      title: 'IMTPaveExpress - Backend (User Management)',
      image: {
        src: 'assets/imtpx_users.png',
        alt: 'IMTPaveExpress User Management - NestJS Backend API',
      },
      duration: 'March 2024 - Aug 2025',
      description: 'projects.imtpx.users.description',
      technologies: [
        'NestJS',
        'TypeScript',
        'PostgreSQL',
        'TypeORM',
        'JWT',
        'Passport',
        'bcrypt',
        'Firebase Admin',
        'Nodemailer',
        'Swagger',
        'Class Validator',
        'Multer',
        'Docker',
        'CORS',
      ],
    },
    {
      title: 'My Portfolio',
      image: {
        src: 'assets/my_portfolio.png',
        alt: 'Personal Portfolio Website - Angular and Tailwind CSS',
      },
      duration: 'August 2025',
      description: 'projects.portfolio.description',
      technologies: ['Angular', 'Tailwind CSS', 'TypeScript'],
      link: 'https://rentheria.com',
    },
  ];
}
